version: 1.0.{build}

environment:
  key_pass:
    secure: UQOSEsEsXFmZvp1k18+7Lbd19NNPEEniq2euQgU0giz3OYHu0qWvQP9qecUayCtagAeG4C75RfwChkS2r+DjWZaePnr2OtPK46sM2pjXTx4=
  pfx_key:
    secure: qBgsWfnk50nFMs/Ft9T6lRx11eudnE17Z+paEtSJJ7tdn9F29Huy4rrw1bDjVC9LrmYch+09hZJm9WHGYuc4YuWPFBlvtngGqYsYD4r2gnQ=


notifications:
  - provider: Slack
    incoming_webhook:
      secure: SyfpZAVQA8PEPdjqqc6Yav3i5wNOCFxNcoHx3oJPYSLs13PdDLpSPKPiYJgxTYogspCIFcskc8nMUkXC0s7P8AWCzTKtusjKchd8D+pJR2I=

branches:
  only:
    - master
    - appveyor
    - windows-setup

clone_folder: c:\projects\lbry

init:
- ps: >-
    $env:Path += ";C:\MinGW\bin\"

    gcc --version

    mingw32-make --version

    mkdir C:\temp

    Invoke-WebRequest "https://pypi.python.org/packages/55/90/e987e28ed29b571f315afea7d317b6bf4a551e37386b344190cffec60e72/miniupnpc-1.9.tar.gz" -OutFile "C:\temp\miniupnpc-1.9.tar.gz"

    cd C:\temp

    7z e miniupnpc-1.9.tar.gz

    7z x miniupnpc-1.9.tar

    cd C:\temp\miniupnpc-1.9

    mingw32-make.exe -f Makefile.mingw

    C:\Python27\python.exe C:\temp\miniupnpc-1.9\setupmingw32.py build --compiler=mingw32

    C:\Python27\python.exe C:\temp\miniupnpc-1.9\setupmingw32.py install

    Invoke-WebRequest "https://github.com/lbryio/lbry/raw/master/packaging/windows/libs/gmpy-1.17-cp27-none-win32.whl" -OutFile "C:\temp\gmpy-1.17-cp27-none-win32.whl"

    C:\Python27\Scripts\pip.exe install "C:\temp\gmpy-1.17-cp27-none-win32.whl"

    C:\Python27\Scripts\pip.exe install pypiwin32==219

    C:\Python27\Scripts\pip.exe install six==1.9.0

    C:\Python27\Scripts\pip.exe install requests==2.9.1

    C:\Python27\Scripts\pip.exe install zope.interface==4.1.3

    C:\Python27\Scripts\pip.exe install cx-freeze==4.3.3

    C:\Python27\Scripts\pip.exe install cython==0.24.1

    C:\Python27\Scripts\pip.exe install Twisted==16.0.0

    C:\Python27\Scripts\pip.exe install Yapsy==1.11.223

    C:\Python27\Scripts\pip.exe install appdirs==1.4.0

    C:\Python27\Scripts\pip.exe install argparse==1.2.1

    C:\Python27\Scripts\pip.exe install colorama==0.3.7

    C:\Python27\Scripts\pip.exe install dnspython==1.12.0

    C:\Python27\Scripts\pip.exe install ecdsa==0.13

    C:\Python27\Scripts\pip.exe install jsonrpc==1.2

    C:\Python27\Scripts\pip.exe install jsonrpclib==0.1.7

    C:\Python27\Scripts\pip.exe install loggly-python-handler==1.0.0

    C:\Python27\Scripts\pip.exe install pbkdf2==1.3

    C:\Python27\Scripts\pip.exe install protobuf==3.0.0

    C:\Python27\Scripts\pip.exe install pycrypto==2.6.1

    C:\Python27\Scripts\pip.exe install python-bitcoinrpc==0.1

    C:\Python27\Scripts\pip.exe install qrcode==5.2.2

    C:\Python27\Scripts\pip.exe install requests_futures==0.9.7

    C:\Python27\Scripts\pip.exe install seccure==0.3.1.3

    C:\Python27\Scripts\pip.exe install simplejson==3.8.2

    C:\Python27\Scripts\pip.exe install slowaes==0.1a1

    C:\Python27\Scripts\pip.exe install txJSON-RPC==0.3.1

    C:\Python27\Scripts\pip.exe install unqlite==0.5.3

    C:\Python27\Scripts\pip.exe install wsgiref==0.1.2

    C:\Python27\Scripts\pip.exe install base58==0.2.2

    C:\Python27\Scripts\pip.exe install googlefinance==0.7

    C:\Python27\Scripts\pip.exe install git+https://github.com/lbryio/lbryum.git

    cd C:\projects\lbry

install:
- ps: >-
    C:\Python27\python.exe setup.py install

    nuget install secure-file -ExcludeVersion

    secure-file\tools\secure-file -decrypt "C:\projects\lbry\packaging\windows\certs\pfx.enc" -secret %pfx_key% -out "C:\projects\lbry\packaging\windows\certs\lbry.pfx"

build_script:
- ps: >-
    C:\Python27\python.exe setup.py build bdist_msi

    signtool sign /f "C:\projects\lbry\packaging\windows\certs\lbry.pfx" /p %key_pass% /tr http://tsa.starfieldtech.com /td SHA256 /fd SHA256 "C:\projects\lbry\dist\*.msi"


test_script:
- ps: >-
    C:\Python27\Scripts\pip.exe install mock

    C:\Python27\Scripts\pip.exe install pylint

    C:\Python27\python.exe C:\Python27\Scripts\trial.py C:\projects\lbry\tests

artifacts:
- path: dist/*.msi
  name: msi
- path: build/exe.win32-2.7/
  name: lbry-portable
- path: packaging/windows/lbry-win32-app/LBRY-URI.reg
  name: LBRY-URI
