version: 1.0.{build}

environment:
  key_pass:
    secure: u6DydPcdrUJlxGL9uc7yQRYG8+5rY6aAEE9nfCSzFyNzZlX9NniOp8Uh5ZKQqX7bGEngLI6ipbLfiJvn0XFnhbn2iTkOuMqOXVJVOehvwlQ=
  pfx_key:
    secure: 1mwqyRy7hDqDjDK+TIAoaXyXzpNgwruFNA6TPkinUcVM7A+NLD33RQLnfnwVy+R5ovD2pUfhQ6+N0Fqebv6tZh436LIEsock+6IOdpgFwrg=


notifications:
  - provider: Slack
    incoming_webhook:
      secure: LuxwG5OZnnA//gmSXzCKu8/FRqYjCgGfVFqajSsGHeQ1HQNp7rYNhQpsO8/3PK63xKJj3wzt86DJekf9q9Q5OcHa9AHXUQbEveX0psd7elw=


clone_folder: c:\projects\lbry

init:
- ps: "$(APPVEYOR_BUILD_FOLDER)\packaging\windows\init.ps1"

install:
- nuget install secure-file -ExcludeVersion
- secure-file\tools\secure-file -decrypt packaging\windows\certs\lbry2.pfx.enc -secret %pfx_key%
- ps: "$(APPVEYOR_BUILD_FOLDER)\packaging\windows\install.ps1"


build_script:
- ps: C:\Python27\python.exe setup.py build bdist_msi
- signtool.exe sign /f packaging\windows\certs\lbry2.pfx /p %key_pass% /tr http://tsa.starfieldtech.com /td SHA256 /fd SHA256 dist\*.msi


test_script:
- ps: "$(APPVEYOR_BUILD_FOLDER)\packaging\windows\test.ps1"


artifacts:
- path: dist/*.msi
  name: msi
- path: build/exe.win32-2.7/
  name: lbry-portable
- path: packaging/windows/lbry-win32-app/LBRY-URI.reg
  name: LBRY-URI


deploy:
  release: $(APPVEYOR_REPO_TAG_NAME)
  description: 'Release'
  provider: GitHub
  auth_token:
    secure: 28gMVxQkXr2iXP4F+5kVwefUtKCfS1ePZ97PVfaSR8UDupjAvKhSJx862TnEjukb
  artifact: dist/*.msi
  draft: false
  prerelease: true
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only
