site_name: LBRY
repo_url: https://github.com/lbryio/lbry
pages:
  - "API": index.md
theme: material 
site_dir: docs_build
google_analytics:
  - 'UA-60403362-1'
  - 'auto'
extra:
  palette:
    primary: 'teal'
    accent: 'green'
  logo: 'images/lbry-white.svg'
  social:
    - type: 'github'
      link: 'https://github.com/lbryio'
    - type: 'twitter'
      link: 'https://twitter.com/lbryio'
    - type: 'facebook'
      link: 'https://facebook.com/lbryio'
